spring:
  rabbitmq:
    username: admin
    password: admin
    addresses: 39.98.231.229:5672
    cache:
      connection:
        #缓存连接模式,默认一个连接,多个channel
        mode: channel
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hw001.zzfactory.com:3307/zz_keystone
    username: root
    password: puckteam
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10000
  # Redis配置
  redis:
    database: 1
    password: Iot@Abc123
    host: r-bp1f7917e7aefe44pd.redis.rds.aliyuncs.com
