spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/,classpath:/views/
  application:
    name: "@project.name@"
    description: "@project.description@"
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hw001.zzfactory.com:3307/zz_keystone
    username: root
    password: puckteam
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 10000
  # Redis配置
  redis:
    database: 1
    password: Iot@Abc123
    host: r-bp1f7917e7aefe44pd.redis.rds.aliyuncs.com

server:
  port: 12200

zz:
  # 基础包的路径需要修改
  basePackage: com.zz
  # 过滤器配置
  filter:
    # 请求路径Filter配置
    request-path:
      enabled: true
      include-paths: /**
      # 排除路径，多行字符串配置
      exclude-paths: |
        /applications/**,/actuator/**,/instances/**,/logfile,/sba-settings.js,/assets/img/fxacon.png,
        /swagger-ui.html,/swagger-resources/**,/webjars/springfox-swagger-ui/**,/v2/api-docs,
        /druid/**,/fxacon.ico,/test/test,/login/add
  shiro:
    # 是否启用
    enable: true
    # util ini 多行字符串配置
    filter-chain-definitions: |
      /=anon
      /static/**=anon
      /verify/**=anon
    # 权限配置
    permission:
      # 排除安全下载
      - urls: /print/download/key/**
        permission: anon
        # 排除静态资源
      - urls: /static/**,/templates/**
        permission: anon
        # 排除Swagger
      - urls: /docs,/swagger-ui.html,/webjars/springfox-swagger-ui/**,/swagger-resources/**,/v2/api-docs
        permission: anon
        # 排除SpringBootAdmin
      - urls: /,/fxacon.ico,/actuator/**,/instances/**,/assets/**,/sba-settings.js,/applications/**
        permission: anon
      - urls: /login/add,/login/login
        permission: anon


  jwt:
    # token请求头名称
    token-name: AccessToken
    # jwt密钥
    secret: 666666
    # 发行人
    issuer: zz
    # 观众
    audience: web
    # 默认过期时间10000小时，单位：秒
    expire-second: 36000000
    # 是否刷新token
    refresh-token: true
    # 刷新token的时间间隔，默认10分钟，单位：秒
    refresh-token-countdown: 600
    # redis校验jwt token是否存在,可选
    redis-check: true
    # true: 同一个账号只能是最后一次登陆token有效，false：同一个账号可多次登陆
    single-login: false
    # 盐值校验，如果不加自定义盐值，则使用secret校验
    salt-check: false

mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  # MyBatis原生配置
  configuration:
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: id_worker
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      db-type: mysql
  # mapper xml映射路径
  mapper-locations: classpath*:mapper/**/**Mapper.xml
